# Generated by Django 6.0.2 on 2026-02-07 04:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arkham_app', '0002_auditlog_medical_file'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='inmate_profile',
            new_name='InmateProfile',
        ),
        migrations.CreateModel(
            name='MedicalFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnosis', models.CharField(max_length=100)),
                ('meds', models.CharField(max_length=150)),
                ('inmate', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='arkham_app.inmateprofile')),
            ],
        ),
        migrations.DeleteModel(
            name='medical_file',
        ),
    ]
