# Generated by Django 6.0.2 on 2026-02-18 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arkham_app', '0003_rename_inmate_profile_inmateprofile_medicalfile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inmateprofile',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('DISCHARGED', 'Discharged'), ('TRANSFERRED', 'Transferred'), ('ESCAPED', 'Escaped'), ('DECEASED', 'Deceased')], default='ACTIVE', max_length=20),
        ),
    ]
