# Generated by Django 6.0.2 on 2026-02-19 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arkham_app', '0004_inmateprofile_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action_type',
            field=models.CharField(choices=[('DETAILED_READ', 'Detailed Read'), ('UPDATE', 'Update'), ('CREATE', 'Create'), ('DELETE', 'Delete')], max_length=50),
        ),
    ]
