# Generated by Django 6.0.2 on 2026-02-19 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arkham_app', '0005_alter_auditlog_action_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inmateprofile',
            name='cell_block',
            field=models.CharField(choices=[('Block-A', 'Block A'), ('Block-B', 'Block B'), ('Block-C', 'Block C'), ('Block-D', 'Block D'), ('Block-E', 'Block E')], max_length=20),
        ),
    ]
