# Generated by Django 6.0.2 on 2026-02-24 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arkham_app', '0007_medicalfile_assigned_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='actor_group',
            field=models.CharField(default='Unknown', max_length=50),
        ),
    ]
