# Generated by Django 6.0.2 on 2026-02-25 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arkham_app', '0008_auditlog_actor_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inmateprofile',
            name='alias',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='inmateprofile',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
