# Generated by Django 6.0.2 on 2026-02-25 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arkham_app', '0009_alter_inmateprofile_alias_alter_inmateprofile_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CellBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('max_capacity', models.PositiveIntegerField(default=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='medicalfile',
            name='diagnosis',
        ),
        migrations.AddField(
            model_name='medicalfile',
            name='internal_diagnosis',
            field=models.CharField(blank=True, default='Pending evaluation', max_length=200),
        ),
        migrations.AddField(
            model_name='medicalfile',
            name='referral_diagnosis',
            field=models.CharField(default='Pre-existing record', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inmateprofile',
            name='cell_block',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inmates', to='arkham_app.cellblock'),
        ),
    ]
